### PR TITLE
The latest spiffs is included as third-party module.

### PR DESCRIPTION
**Pull request by slaff**
This change will allow us to update the Spiffs version to the latest one. Related to #815.

Please, test it on your ESP8266 devices and send us your feedback.

This PR will not be merged until we are 99% sure that it behaves nicely with the existing samples.

### CODE REVIEW

**Comment by kwis2** [comment]
I am beginer in github, ESP git and even gcc, so there could be sth I make wrong. Additionally I work on windows....  
I have downloaded commit Sming-34a44cd428069b443f43472fa8fbad1e51bcbef0, copied into c:/tools/sming/ and there are some problems. With make command I have received 

> C:\tools\sming\Sming>make
> Fetching third-party/rboot/ ...
> fatal: Not a git repository (or any of the parent directories): .git
> make: *** [third-party/rboot/Makefile] Error 128

while third-party/rboot/ dir is empty

on the other hand I have tried to compile program and get

> c:\tools\sming\sming\services\spiffs\spiffs_sming.h:8:20: fatal error: spiffs.h: No such file or directory
> compilation terminated.

I have checked sming dir and there is no spiffs.h

**Comment by kwis2** [comment]
I have to learn a lot ....
finally project compiled, for the first look, it looks that there is no problem with SPIFFS anymore. 
For my windows I had to change in Makefile-project.mk
```
34 # esptool2 path
35 ESPTOOL2 ?= esptool2
```
to 
`35 ESPTOOL2 ?= c:/Espressif/utils/esptool2`

**Comment by slaff** [comment]
@kwis2 Thanks for your help :)

**Comment by kwis2** [comment]
filestem works until I would like to connect via ftp. 
module ESP8266-01 read once (I use WinSCP) then hangs

>  ets Jan  8 2013,rst cause:4, boot mode:(1,7)
> 
> wdt reset

**Comment by kwis2** [comment]
I am to green to identyfy problem, so the best way it is to send example of code which work fine in v2.15. 
I have simplified program to test  [ftp problem](https://github.com/kwis2/test_SMING.git) code is beginer compilation of sming examples. to measure every 20s sensor data. data written to file and then it was send http get (removed for simplify). connection to router by ESP TOUCH or by 
`11 #define SmartConfig` 
and
`206 ssid = "xxxxx";`
`207 password = "yyyyy";`
after some time - a few measurements with active connection I have tried to connect ftp and get

> Fatal exception 28(LoadProhibitedCause):
> epc1=0x40247223, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000002c, depc=0x00000000
> 
>  ets Jan  8 2013,rst cause:2, boot mode:(1,7)
> 
>  ets Jan  8 2013,rst cause:4, boot mode:(1,7)
>
> wdt reset

or another time

> Fatal exception 28(LoadProhibitedCause):
> epc1=0x402458b7, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000002c, depc=0x00000000
> 
>  ets Jan  8 2013,rst cause:2, boot mode:(1,7)
> 
> 
>  ets Jan  8 2013,rst cause:4, boot mode:(1,7)
> 
> wdt reset

and after reset module fail to work - infinite loop

> init T
> odczyt T
> wynik_001.dat
> pm open,type:2 0
> Fatal exception 28(LoadProhibitedCause):
> epc1=0x40247223, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000002c, depc=0x00000000
> 
>  ets Jan  8 2013,rst cause:2, boot mode:(3,7)
> 
> load 0x40100000, len 23572, room 16 
> tail 4
> chksum 0x71
> load 0x3ffe8000, len 904, room 4 
> tail 4
> chksum 0xb8
> load 0x3ffe8388, len 8064, room 4 
> tail 12
> chksum 0x10
> csum 0x10
> don't use rtc mem data
> rl¦+TCP connection
> timeout updating: 70 -> 65535
> Server timeout updating: 40 -> 900
> +TCP connection
> timeout updating: 70 -> 65535
> Server timeout updating: 40 -> 90
> +TCP connection
> fs.start: size:192 Kb, offset:0x4c000
> mount res: 0
> 
> 
> mode : sta(5c:cf:7f:16:7a:6b)
> add if0
> f r0, scandone
> state: 0 -> 2 (b0)
> state: 2 -> 3 (0)
> state: 3 -> 5 (10)
> add 0
> aid 4
> cnt 
> chg_B1:-40
>

**Comment by slaff** [comment]
Tested on real device: Listing, reading content and writing is working.
```C
        Vector<String> list = fileList();
	debugf("Total files: %d", list.count());
	for (int i = 0; i < list.count(); i++) {
		debugf("%s: %d\n", list[i].c_str(), fileGetSize(list[i]));
	}
```

**Comment by kwis2** [comment]
With [00c7736](https://github.com/SmingHub/Sming/commit/00c77364afbc441e86f8b3b7910ca3ffecd6750f) there is still problem with filesystem. I have tried my programs, and the simplest example it is just sming FtpServer_Files example.
While connect to ftp I got loop. (I have tried with `SPIFF_FILES = files` and `SPIFF_FILES = web`) and from WinSCP (my translation) `timeout`, `error while read '/' folder`

> PORT: '192,168,0,8,10,109'
> connection to: 192.168.0.8, 2669
> > 200 OK
> 
> LIST: '-a'
> +TCP connection
> TcpConnection::connect result:, 0
> > 150 Connecting
> 
> OnConnected
> timeout updating: 70 -> 300
> TCP connected
> send file list: 2
> TCP connection closing
> ~TCP connection
> > 226 Transfer Complete.
> 
> TCP sent: 92
> 
>  ets Jan  8 2013,rst cause:4, boot mode:(3,7)
> 
> wdt reset
> il 4
> chksum 0x20
> load 0x3ffe8000, len 884, room 4 
> tail 0
> chksum 0x05
> scandone
> state: 0 -> 2 (b0)
> state: 2 -> 3 (0)
> load 0x3ffe8378, len 6196, room 8 
> tail 12
> chksum 0x43
> csum 0x43
> -> 5 (10)
> add 0
> aid 3
> cnt 
> 
> connected with XXXXXX, channel 6
> dhcp client start...
> chg_B1:-40
> rl+TCP connection
> timeout updating: 70 -> 65535
> Server timeout updating: 40 -> 900
> fs.start: size:224 Kb, offset:0x44000
> mount res: 0
> 
> 
> Station configuration is: XXXXXX
> mode : sta(5c:cf:7f:84:86:68)
> add if0
> annel 6
> dhcp client start...
> chg_B1:-4ip:192.168.0.19,mask:255.255.255.0,gw:192.168.0.1
> 
> I'm CONNECTED:
> 192.168.0.19
> addUser: me 123
> onAccept state: 0 K=0
> Free heap size=43928, K=0
> +TCP connection
> timeout updating: 70 -> 900
> TcpServer onClient: 192.168.0.8
> 
> USER: 'me'
> > 331 OK
> 
> PASS: '123'
> checkUser: me 123
> > 230 OK
> 
> SYST: ''
> > 215 Windows_NT: Sming Framework
> 
> FEAT: ''
> > 502 Not supported
> 
> PWD: ''
> > 257 "/"
> 
> CWD: '/'
> > 250 OK
> 
> PWD: ''
> > 257 "/"
> 
> TYPE: 'A'
> > 250 OK
> 
> PORT: '192,168,0,8,10,111'
> connection to: 192.168.0.8, 2671
> > 200 OK
> 
> LIST: ''
> +TCP connection
> TcpConnection::connect result:, 0
> > 150 Connecting
> 
> OnConnected
> timeout updating: 70 -> 300
> TCP connected
> send file list: 2
> TCP connection closing
> ~TCP connection
> > 226 Transfer Complete.

**Comment by kwis2** [comment]
Maybe it could help.
I have tested a little and in my opinion the problem it is ftp listing of '/' folder . www server with files work ok, additionally when I have reprogrammed ESP with new commit sming while it was connected to ftp with software complied in sming 2v15 ftp works fine when I have asked for files, and hangs when I have refresh filelist.

**Comment by slaff** [comment]
> With 00c7736 there is still problem with filesystem.

The problem is still there but it is, most probably, not caused from the SpifFS. We need to investigate further the FTPServer code to see what is causing the issue. I will try to add more out-of-the-box debugging information that can show us more what or where is the reason for WDT resets ( The Fatal causes are already handled from #821 )

**Comment by hreintke** [comment]
@slaff @kwis2 
There are issues in the FTP implementation within SmingNONOS which cause  symptoms you describe.
I encountered (and solved) them when converting to SmingRTOS.
You should check RTOS vs NONOS FTP for the differences

**Comment by slaff** [comment]
> I encountered (and solved) them when converting to SmingRTOS.

@hreintke It will be great if you can help us here :)
