### ISSUE TITLE
Windows 7 64 bit Quick Start Guide Produce Error: 

### ISSUE THREAD

**Issue by sonic238** [SmingHub/Sming#566]
I'm following https://github.com/SmingHub/Sming/wiki/Windows-Quickstart and got this error:

make all 
C+ app/application.cpp
In file included from c:\tools\sming\sming\smingcore\network\ntpclient.h:8:0,
                 from c:/tools/sming/Sming/SmingCore/SystemClock.h:7,
                 from c:/tools/sming/Sming/SmingCore/SmingCore.h:18,
                 from app/application.cpp:2:
c:\tools\sming\sming\smingcore\platform\station.h:36:25: error: 'SC_TYPE_ESPTOUCH_AIRKISS' was not declared in this scope
  SCT_EspTouch_AirKiss = SC_TYPE_ESPTOUCH_AIRKISS
                         ^
make: *** [out/build/app/application.o] Error 1

******************************************
maker

'SC_TYPE_ESPTOUCH_AIRKISS' was not declared in this scope

make: *** [out/build/app/application.o] Error 1

**Comment by hreintke** [comment]
You are using an incompatible combination of sming and espressif sdk.
Sming 2.1.0 only works with sdk 1.4.0 and sdk 1.5.0

**Comment by sonic238** [comment]
I need to fix my help .
I have no knowledge in this field.

**Comment by hreintke** [comment]
Please discuss installation issues in https://gitter.im/SmingHub/Sming
